import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, realpath, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import * as sources from '../src/sources/service.mjs';
import { createOwnedSourceProfile } from '../src/sources/owned-profile.mjs';
const desktop = await import('../src/codex/replay-desktop.mjs').catch(e => { if (e.code === 'ERR_MODULE_NOT_FOUND') return {}; throw e; });
test('Mac desktop admission follows the registered executable bundle identity even when its app is renamed', { skip: process.platform !== 'darwin' }, async t => {
  const parent = await realpath(await mkdtemp(join(tmpdir(), 'unharness-app-identity-'))); t.after(() => rm(parent, { recursive: true, force: true }));
  const bundle = join(parent, 'Renamed Desktop.app'), executable = join(bundle, 'Contents/Resources/codex');
  await mkdir(join(bundle, 'Contents/Resources'), { recursive: true }); await writeFile(executable, 'unused synthetic executable');
  const plist = id => `<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>${id}</string></dict></plist>`;
  await writeFile(join(bundle, 'Contents/Info.plist'), plist('com.openai.codex'));
  assert.equal(typeof desktop.findReplayDesktopBundle, 'function');
  assert.equal(await desktop.findReplayDesktopBundle(executable), bundle);
  await writeFile(join(bundle, 'Contents/Info.plist'), plist('invalid.other-app'));
  assert.notEqual(await desktop.findReplayDesktopBundle(executable), bundle);
});
test('open hands only the guarded owned path to the native app command and never submits the frozen request', { skip: process.platform !== 'darwin' }, async t => {
  const parent = await realpath(await mkdtemp(join(tmpdir(), 'unharness-open-replay-'))); t.after(() => rm(parent, { recursive: true, force: true }));
  const profile = await createOwnedSourceProfile({ parent, executable: resolve('test-support/user-source-server.mjs') });
  const d = await sources.discoverUserSources(profile.context);
  const { workspace } = await sources.registerUserSources({ context: profile.context, discoveryId: d.discoveryId, instructionsOptional: true, selectedSkillIds: [], userAddedOptional: true });
  const r = await sources.reviewUserStart({ workspace, declaration: { request: 'PRIVATE task request', requirements: [{ id: 'done', label: 'Done', critical: true }], ratings: [], budget: { maxAttempts: 1, maxTurnsPerAttempt: 1, maxRecordedTokens: null } } });
  const start = await sources.saveUserStart({ workspace, reviewId: r.reviewId });
  const review = await sources.reviewUserReplay({ workspace, startId: start.startId });
  const p = await sources.prepareUserReplay({ workspace, reviewId: review.reviewId });
  assert.equal(typeof desktop.setReplayDesktopRunnerForTest, 'function');
  const calls = [];
  desktop.setReplayDesktopRunnerForTest(async value => { calls.push({ executable: value.executable, args: value.args, codexHome: value.options.env.CODEX_HOME }); });
  t.after(() => desktop.setReplayDesktopRunnerForTest(null));
  assert.equal(typeof sources.openUserReplay, 'function');
  const opened = await sources.openUserReplay({ workspace, attemptId: p.attemptId });
  assert.equal(opened.desktopOpenRequested, true); assert.equal(opened.taskSubmitted, false); assert.equal(opened.desktopHomeVerified, false);
  assert.deepEqual(calls, [{ executable: profile.context.executable, args: ['app', p.project], codexHome: profile.context.codexHome }]);
  assert.ok(!JSON.stringify(calls).includes('PRIVATE task request'));
  await writeFile(join(p.project, 'extra-input.txt'), 'Independent input');
  await assert.rejects(sources.openUserReplay({ workspace, attemptId: p.attemptId }), { kind: 'replay-destination-changed' });
  assert.equal(calls.length, 1);
});
