export type Locale = 'ja' | 'en';
export type Scenario = 'first' | 'update' | 'returning';
export type Stage = 'welcome' | 'inventory' | 'proposal' | 'prepared' | 'ready' | 'update' | 'reload' | 'updated';
const en = {
  preview: 'INTERACTIVE CONCEPT', previewNote: 'Demo actions use sample data. Open-in-Codex links, external links and copying are real.',
  startInCodex: 'Start Unharness in Codex', openInCodex: 'Open the request in Codex',
  nativeHint: 'In Codex, review the request and send it. If the app does not open, use the copy option.',
  copyAlternative: 'Review or copy the request',
  skip: 'Skip to content', navDemo: 'Try the guide', navHow: 'How it works', navInstall: 'Get started',
  tagline: 'Find your fit.', heroEyebrow: 'YOUR AI. YOUR LOADOUT.',
  heroFirst: 'New model.', heroSecond: 'Same old harness?',
  heroLead: 'Before rewriting it, try taking it off.',
  heroBody: 'Keep your usual setup. Try a lighter set of instructions and Skills. Let your everyday work show you what fits.',
  heroPrimary: 'Try the AI-guided experience',
  installedEntry: 'Already installed? See what happens next',
  availability: 'Free & open source · Apple Silicon Mac + Codex Desktop',
  future: 'Windows Codex next. Claude Code afterward.',
  modeLabel: 'Mode preview', modes: { normal: 'Normal', unseal: 'UNSEAL', trueform: 'TRUEFORM' },
  modeNotes: {
    normal: 'Your saved, everyday setup.',
    unseal: 'Start from TRUEFORM and add the Skills you need.',
    trueform: 'Try selected optional instructions off, with Skills disabled or called explicitly.',
  },
  appearanceLabel: 'Appearance', looks: { default: 'Original', silver: 'Silver', amber: 'Amber' },
  effects: 'Animation', appearanceNote: 'Your look is yours. It does not change your settings or measure performance.',
  sceneEyebrow: 'TRY ON A DIFFERENT LOADOUT',
  journeyTitle: 'You bring the AI.\nWe help with the next step.',
  journeyBody: 'You do not need to know the right command. Ask to open Unharness, and start from where you are.',
  journeySteps: ['Ask your AI to open it', 'Review the next suggestion', 'Try it in a fresh task'],
  journeyDescriptions: [
    'See your current state and any available update.',
    'Keep Normal, choose what to try, or revisit a Skill.',
    'Prepare a mode, use it for real work, and keep what fits.',
  ],
  scenariosLabel: 'Choose a sample situation',
  scenarios: { first: 'First time', update: 'Update available', returning: 'Already set up' },
  guideEyebrow: 'A GUIDED FIRST STEP', guideTitle: 'Just ask to open it.',
  guideLead: 'Follow a short sample conversation. Choose the next action and see its result.',
  you: 'YOU', ai: 'UNHARNESS GUIDE', askOpen: 'Open Unharness.',
  sampleState: 'SAMPLE SETTINGS', selectedPreview: 'Previewing', preparedLabel: 'Prepared mode',
  notSaved: 'Not saved yet', normalSaved: 'Normal saved', sampleVersion: 'Sample local version',
  next: 'NEXT SUGGESTION', protected: 'Project requirements, memory, permissions and official plugins stay in place.',
  scopeTitle: 'Choose what belongs in this comparison.',
  scopeLead: 'This sample includes optional global instructions and ordinary Skills. Your real setup would be reviewed on this Mac.',
  scopeNames: ['Global AGENTS.md', 'Your own Skills', 'Added third-party Skills'],
  scopeValues: ['One optional instruction source', 'Two sample Skills', 'Three sample Skills'],
  reviewed: 'I have reviewed these sample targets.',
  reviewHint: 'Review the targets to continue.',
  proposalTitle: 'Two ways to try it.',
  instructions: 'Global instructions', ownSkills: 'Your own Skills', externalSkills: 'Added Skills',
  keep: 'Saved instructions', minimal: 'Minimal guide', removed: 'Selected instructions off',
  automatic: 'Automatic', manual: 'Explicit use', disabled: 'Disabled',
  proposalNote: 'Normal stays saved. These are comparison options for your work, not a ranking of model performance.',
  openConfirm: 'Review the sample targets', saveNormal: 'Save Normal & see suggestions',
  trySelected: 'Prepare this sample mode', consult: 'Ask AI to adjust it',
  freshTask: 'See the next-task guidance', backGuide: 'Back to the guide',
  startupPrompt: 'An update can wait. Your current setup stays available.',
  updateNow: 'Preview the update steps', updateLater: 'Keep using this version',
  updateChangeTitle: 'What changes in 0.0.9',
  updateChanges: ['Clearer mode, settings and appearance pages', 'Chat entry points beside the controls', 'Better explanations when an action is blocked'],
  updateKeeps: 'Saved Normal, settings and artwork are kept.',
  reloadNext: 'Continue the sample after reloading', retry: 'Try this situation again',
  skillTitle: 'Want to revisit a Skill?',
  skillBody: 'Ask for a review of selected Skill content using guidance for your model. Choose the changes you want to adopt.',
  skillAction: 'See a Skill-review request', skillBoundary: 'Editing Skill content is separate from changing how a mode uses it.',
  dialogLabel: 'Use this with your AI', dialogClose: 'Close',
  copy: 'Copy request', copied: 'Copied. Paste it into your Codex chat.',
  copyFailed: 'Copy was unavailable. Select the request below and copy it.',
  requestLabel: 'Request for your AI', copyBoundary: 'Copying a request does not send it or change your configuration.',
  installEyebrow: 'START WITH YOUR OWN AI', installTitle: 'Let Codex guide you in.',
  installBody: 'Open the request in Codex Desktop. Your AI checks whether Unharness is installed, then guides installation or the next useful action.',
  targetLabel: 'Available preview', targetValue: 'Apple Silicon Mac · Codex Desktop',
  releasePrefix: 'Published version',
  installAfter: 'After installation', installOpen: 'Open Unharness.',
  installAfterBody: 'Your AI checks the connection and guides you through reviewing targets and saving Normal.',
  seeFirst: 'Preview the first-time guide', advanced: 'Download and source details',
  zip: 'Download the Mac ZIP', release: 'Release notes & checksums', source: 'Source code',
  offline: 'Your settings and artwork stay on your computer. Your chosen AI subscription and usage are separate.',
  howEyebrow: 'FROM “OPEN IT” TO YOUR NEXT TASK', howTitle: 'One useful suggestion at a time.',
  howBody: 'The guide responds to your stage. A direct request, such as switching a saved mode, goes straight to that action.',
  howRows: [
    ['An update is available', 'Explain what changes. Update now or keep using the current version.'],
    ['You are here for the first time', 'Review the selected sources and keep your usual configuration as Normal.'],
    ['You are ready to try a mode', 'Review TRUEFORM and UNSEAL, prepare one, then use a fresh task.'],
    ['A model or Skill has changed', 'Offer a focused review. Previous choices and saved versions stay available.'],
  ],
  howFoot: 'This concept demonstrates the conversation and screens. Real update detection and runtime verification are implementation work still to come.',
  footer: 'Your settings. Your computer. Your choice.',
  feedback: 'Report an issue', openSite: 'Current public site',
  stages: {
    welcome: ['Let’s keep your starting point.', 'First, review the optional instructions and Skills you want to compare. Your current configuration will be saved as Normal.'],
    inventory: ['Review first. Keep a way back.', 'Here are the sample targets. Required project rules and the rest of your environment stay in place.'],
    proposal: ['Normal is saved in this sample.', 'You can now try two comparison setups. Choose a preview, then prepare the one you want to use.'],
    prepared: ['Ready for a fresh task.', 'The sample mode is prepared. That does not change what this conversation has already loaded.'],
    ready: ['Your saved setup is ready.', 'Preview a different mode, revisit the settings, or choose a look. What would you like to try today?'],
    update: ['A new version is available.', 'This sample has 0.0.8 installed and offers 0.0.9. Review the changes before choosing whether to update.'],
    reload: ['Update prepared. One step remains.', 'In the real flow, we would guide the required reload or restart, then check the running version and Skill loading. Downloading alone is not completion.'],
    updated: ['The update flow is complete in this sample.', 'The sample now shows 0.0.9 running. Your saved configuration remains Normal, and you can continue using it.'],
  },
};
type Copy = typeof en;
const ja: Copy = {
  preview: '操作できる画面案', previewNote: 'デモはサンプルです。Codexで開く・外部リンク・コピーは実際の操作です。',
  startInCodex: 'CodexでUnharnessを始める', openInCodex: 'Codexで依頼を開く',
  nativeHint: 'Codexの入力欄で内容を確認して送信してください。開かない場合はコピーできます。',
  copyAlternative: '依頼文を確認・コピー',
  skip: '本文へ移動', navDemo: 'デモ', navHow: '使い方', navInstall: '導入',
  tagline: '装備を見直す。', heroEyebrow: 'いつものAIを、今の自分に。',
  heroFirst: 'モデルは変わった。', heroSecond: '装備は、そのまま？',
  heroLead: '書き直す前に、一度外して使ってみる。',
  heroBody: 'いつもの構成を残して、指示やSkillを少し身軽に。ふだんの仕事で試し、自分に合う組み合わせを見つけましょう。',
  heroPrimary: 'AIとの進め方を体験する',
  installedEntry: '導入済みの方：次にできることを見る',
  availability: '無料・オープンソース · Apple Silicon Mac / Codex Desktop',
  future: '次はWindows版Codex、その後にClaude Code。',
  modeLabel: 'モードのプレビュー', modes: { normal: '通常', unseal: '限定解除', trueform: '零式' },
  modeNotes: {
    normal: '保存しておいた、いつもの構成。',
    unseal: '零式を土台に、必要なSkillや最小限の指示を加える。',
    trueform: '選んだ追加指示を外し、Skillを無効または手動で試す。',
  },
  appearanceLabel: '外観', looks: { default: 'デフォルト', silver: '白銀', amber: '琥珀' },
  effects: 'アニメーション', appearanceNote: '好きな姿は自由に。外観を選んでも設定や性能評価は変わりません。',
  sceneEyebrow: 'モードを選んで、装備を試着。',
  journeyTitle: '「開いて」から、\n次の一手まで。',
  journeyBody: '操作方法や依頼文を覚えなくても大丈夫。いつものAIが、今の状態に合わせて案内します。',
  journeySteps: ['いつものAIに頼む', '提案を見て、選ぶ', '新しいタスクで試す'],
  journeyDescriptions: [
    '接続先と現在の状態、更新の有無を確認。',
    'Normalを残し、試す構成や見直すSkillを選ぶ。',
    'モードを準備して、ふだんの仕事で使ってみる。',
  ],
  scenariosLabel: '体験する場面',
  scenarios: { first: '初めて使う', update: '更新がある', returning: '設定済み' },
  guideEyebrow: 'AIが、次の一手をご案内。', guideTitle: 'まずは「開いて」で。',
  guideLead: '短い会話のサンプルです。次の行動を選ぶと、案内と画面が変わります。',
  you: 'あなた', ai: 'UNHARNESSからの案内', askOpen: 'アンハーネスを開いて。',
  sampleState: 'サンプルの設定', selectedPreview: '表示中のプレビュー', preparedLabel: '現在の準備',
  notSaved: '未保存', normalSaved: 'Normal保存済み', sampleVersion: 'サンプルの本体',
  next: '次にできること', protected: 'プロジェクトの必須条件・メモリ・権限・公式プラグインは保持します。',
  scopeTitle: '今回、比較する対象を確認。',
  scopeLead: 'このサンプルでは共通の追加指示と通常のSkillを扱います。実際には、このMacの確認画面で対象を選びます。',
  scopeNames: ['グローバルAGENTS.md', '自作Skill', '追加した外部Skill'],
  scopeValues: ['任意の追加指示 1件', 'サンプルのSkill 2件', 'サンプルのSkill 3件'],
  reviewed: 'このサンプルの対象を確認しました。',
  reviewHint: '対象を確認すると、次へ進めます。',
  proposalTitle: '試し方は、2つ。',
  instructions: '共通の追加指示', ownSkills: '自作Skill', externalSkills: '外部Skill',
  keep: '保存した指示', minimal: '最小ガイド', removed: '選んだ指示を外す',
  automatic: '自動で使う', manual: '自分で呼び出す', disabled: '使わない',
  proposalNote: 'Normalは保存したまま。どちらも仕事で比べるための構成案で、性能の順位ではありません。',
  openConfirm: 'サンプルの対象を確認する', saveNormal: 'Normalを保存して、提案を見る',
  trySelected: 'この構成を準備する', consult: '調整をAIに相談',
  freshTask: '次のタスクへの案内を見る', backGuide: '案内へ戻る',
  startupPrompt: '更新は後でも大丈夫。今の構成を引き続き使えます。',
  updateNow: '更新の流れを見る', updateLater: '今の版で続ける',
  updateChangeTitle: '0.0.9で変わること',
  updateChanges: ['モード・設定・外観の操作を整理', 'チャットからの依頼例を追加', '操作できない理由と次の入口を分かりやすく'],
  updateKeeps: '保存したNormal・設定・作品は引き継ぎます。',
  reloadNext: '再読み込み後のサンプルへ', retry: 'この場面を最初から',
  skillTitle: 'Skillの内容も、見直したくなったら。',
  skillBody: '使っているモデルの公式ガイドを参考に、選んだSkillの改善案を相談できます。採用したい変更を選んで進めます。',
  skillAction: 'Skill見直しの依頼例を見る', skillBoundary: 'Skill本文の改善と、モードごとの使い方の変更は別の操作です。',
  dialogLabel: 'いつものAIへ、この依頼を。', dialogClose: '閉じる',
  copy: '依頼文をコピー', copied: 'コピーしました。Codexのチャットに貼り付けてください。',
  copyFailed: 'コピーできませんでした。下の依頼文を選択してコピーしてください。',
  requestLabel: 'AIへの依頼文', copyBoundary: 'コピーだけでは送信や設定変更は行われません。',
  installEyebrow: 'いつものAIから、はじめる。', installTitle: '導入も、Codexに頼もう。',
  installBody: '依頼文をCodex Desktopで開きます。導入済みかどうかをAIが確認し、導入や次にできることを案内します。',
  targetLabel: '現在の対応', targetValue: 'Apple Silicon Mac · Codex Desktop',
  releasePrefix: '公開している版',
  installAfter: '導入が済んだら', installOpen: 'アンハーネスを開いて。',
  installAfterBody: 'AIが接続を確認し、対象の確認とNormal保存へ案内します。',
  seeFirst: '初回の案内を体験する', advanced: '配布物・ソースを自分で確認',
  zip: 'Mac版ZIPをダウンロード', release: '更新内容・照合ファイル', source: 'ソースコード',
  offline: '設定と作品は手元のPCに。普段使うAIの契約・使用量は別です。',
  howEyebrow: '起動してから、実際に使うまで。', howTitle: '今の状態に合う、次の一手を。',
  howBody: '毎回、全部を設定し直す必要はありません。「零式にして」など、具体的な依頼があるときは、その作業へ直接進みます。',
  howRows: [
    ['更新があるとき', '変更内容を説明し、更新するか、今の版を使うかを選びます。'],
    ['初めて使うとき', '対象を確認し、いつもの構成をNormalとして残します。'],
    ['構成を試す準備ができたら', '零式と限定解除の案を確認。一つを準備して、新しいタスクで試します。'],
    ['モデルやSkillが変わったとき', '必要な部分の見直しを提案。以前の選択や保存した版も残します。'],
  ],
  howFoot: 'この画面案では会話と画面の流れを体験できます。実際の更新確認・反映検証は、今後の実装対象です。',
  footer: '設定も、作品も、選択も。あなたの手元に。',
  feedback: '不具合を報告', openSite: '現在の公開サイト',
  stages: {
    welcome: ['まず、いつもの構成を残しましょう。', '比較したい追加指示やSkillを確認します。今の構成はNormalとして保存し、戻れるようにします。'],
    inventory: ['確認してから、戻れる形で。', 'これがサンプルの対象です。プロジェクトの必須条件や、その他の環境は保持します。'],
    proposal: ['サンプルのNormalを保存しました。', '今の構成を残したまま、2つの構成を試せます。プレビューを選び、使ってみたいものを準備しましょう。'],
    prepared: ['新しいタスクで試す準備ができました。', 'サンプルのモードを準備しました。この会話が、すでに読み込んだ内容まで変わるわけではありません。'],
    ready: ['いつもの構成が使えます。', '違うモードを試す、設定を相談する、好きな姿を選ぶ。今日は、どこから始めましょう。'],
    update: ['新しい版が公開されています。', 'このサンプルは本体0.0.8から、0.0.9へ更新する場面です。変更内容を確認して、今更新するか選べます。'],
    reload: ['更新の準備完了。反映まで、あと一歩。', '実際には必要な再読み込みや再起動を案内し、動作中の版とSkillの読み込みを確認します。取得だけでは更新完了にしません。'],
    updated: ['サンプルでの更新が完了しました。', 'サンプルでは0.0.9が動いています。保存したNormalはそのまま。続けて、いつもの構成を使えます。'],
  },
};
export const copy = { en, ja };
