export type EntityMode = 'normal' | 'unseal' | 'trueform';
export type EntityFrameId = EntityMode | `unfold-${number}`;
export type EntityProfileId = 'entity-awakening/v1' | 'entity-awakening/v2';
export const ENTITY_PROFILE_ID: 'entity-awakening/v1';
export const ENTITY_MOTION_PROFILE_ID: 'entity-awakening/v2';
export const ENTITY_MODES: readonly EntityMode[];
export const ENTITY_UNFOLD_FRAMES: readonly EntityFrameId[];
export const ENTITY_MOTION_FRAMES: readonly EntityFrameId[];
export const ENTITY_SHEETS: Readonly<Record<'entity-poses'|'entity-motion',Readonly<{profileId:EntityProfileId;frames:readonly EntityFrameId[]}>>>;
export const ENTITY_ANCHOR: Readonly<{x:number;y:number}>;
export const ENTITY_RELEASE_CENTERS: Readonly<Record<EntityMode,number>>;
export const ENTITY_MAX_HEIGHT: number;
export const ENTITY_CROWN_FRACTION: number;
export function entityPointFits(mode: EntityMode,x:number,y:number): boolean;
export function entityModeAtRelease(release:number): EntityMode;
export function entityFrameAtRelease(profileId:EntityProfileId,release:number): EntityFrameId;
export function entityMotion(mode: EntityMode,time:number,effects:boolean): {y:number;emission:number;crown:number;field:number};
export function entityAssetIds(manifest: unknown): string[];
export function entityFrameAssets(manifest:unknown): Array<{frameId:EntityFrameId;mode:EntityMode;assetId:string}>;
export function validEntityLayer(entity:unknown, version:unknown, assetIds:ReadonlySet<string>): boolean;
export function entityEmission(r:number,g:number,b:number): {strength:number;theme:'cyan'|'amber';color:number};
